# Copyright (c) 2026 Olbutov Aleksandr
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

repos:
  - repo: local
    hooks:
      - id: go-fmt
        name: gofmt
        entry: gofmt -w
        language: system
        types: [go]

      - id: go-vet
        name: go vet
        entry: go vet ./...
        language: system
        pass_filenames: false

      - id: go-test
        name: go test
        entry: go test ./... -short
        language: system
        pass_filenames: false

      - id: check-commit-message
        name: Check Commit Message Format
        entry: bash ./scripts/validate-commit-msg.sh
        language: system
        stages: [commit-msg]

      - id: add-license
        name: Add License Headers
        entry: addlicense -c "Olbutov Aleksandr" -l mit -ignore **/docs/** .
        language: system
        stages: [pre-push]
        pass_filenames: false

      - id: swag-fmt
        name: Swag Format
        entry: swag fmt
        language: system
        stages: [pre-push]
        pass_filenames: false

      - id: swag-init
        name: Swag Init
        entry: swag init -g cmd/WarhammerCalcServer/main.go
        language: system
        stages: [pre-push]
        pass_filenames: false