repos:
  - repo: local
    hooks:
      - id: go-fmt
        name: gofmt
        entry: gofmt -w
        language: system
        types: [go]

      - id: go-vet
        name: go vet
        entry: go vet ./...
        language: system
        pass_filenames: false

      - id: go-test
        name: go test
        entry: go test ./... -short
        language: system
        pass_filenames: false

      - id: check-commit-message
        name: Check Commit Message Format
        entry: bash ./scripts/validate-commit-msg.sh
        language: system
        stages: [commit-msg]

      - id: add-license
        name: Add License Headers
        entry: addlicense -c "Olbutov Aleksandr" -l mit -ignore **/docs/** .
        language: system
        stages: [pre-push]
        pass_filenames: false

      - id: swag-fmt
        name: Swag Format
        entry: swag fmt
        language: system
        stages: [pre-push]
        pass_filenames: false

      - id: swag-init
        name: Swag Init
        entry: swag init -g cmd/WarhammerCalcServer/main.go
        language: system
        stages: [pre-push]
        pass_filenames: false